version: '3.8'

services:
  postgres:
    image: postgres:latest
    container_name: postgres
    restart: unless-stopped
    ports:
      - '5432:5432'
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: forex-trading-system-db
    networks:
      - backend-network
    volumes:
      - pgdata:/var/lib/postgresql/data

  redis:
    container_name: redis-db
    image: redis
    ports:
      - 6379:6379
    networks:
      - backend-network
    restart: unless-stopped
    environment:
      REDIS_PASSWORD: forex-trading-system-redis
    volumes:
      - redis:/data

networks:
  backend-network:
    driver: bridge

volumes:
  pgdata:
  redis:
    driver: local
